# Generated by Django 6.1.1 on 2026-09-22 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('cupos', models.IntegerField()),
                ('estado', models.CharField(choices=[('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('invalido', 'Invalido')], max_length=20)),
                ('motivo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
